version: '3.2'
services:
  
  postgredb:
    build: postgredb/.
    ports:
      - "5432:5432"
  
  service-registry:
    build: service-registry/target/.
    ports:
     - "8761:8761"
    depends_on:
      - "postgredb"
    links:
      - postgredb
    restart: always
   
  user:
    build: user/target/.
    ports:
     - "8180:8180"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always
  
  uaa:
    build: uaa-service/target/.
    ports:
     - "9999:9999"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always
  
  api-gateway:
    build: api-gateway/target/.
    ports:
     - "8080:8080"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always
  
  vrp:
    build: vrp/target/.
    ports:
     - "8580:8580"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always

  truck:
    build: truck-service/target/.
    ports:
     - "8480:8480"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always

  load:
    build: load-service/target/.
    ports:
     - "8380:8380"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always
  
  ui:
    build: ui/target/.
    ports:
     - "8280:8280"
    depends_on:
      - "service-registry"
      - "postgredb"
    links: 
      - postgredb
    restart: always

  

  
  
  

  
  
    


    
