spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway

# Define the port where the API gateway server would be running
server:
  port: 8080

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
  routes:
    user-service:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /api/user/**
      stripPrefix: false
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
    ui-service:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /**
      stripPrefix: false
    load-service:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /api/loads/**
      stripPrefix: false
    truck-service:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /api/trucks/**
      stripPrefix: false
    vrp-service:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      path: /api/vrp/**
      stripPrefix: false
  add-proxy-headers: true
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://uaa-service/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

logging:
  level.org.springframework.security: DEBUG

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
        timeout:
          enabled: false
