server:
  port: 8580

app:
  url: localhost:8080

spring:
  application:
    name: vrp-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vrp
    username: vanya
    password: 123456
  jpa:
    ddl-auto: update
    generate-ddl: true
  maill:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: diplomV7@gmail.com
    password: lbgkjvD7
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: mv8000
        starttls:
          enable: true


################### JavaMail Configuration ##########################
support:
  email: diplomV7@gmail.com

eureka:
  instance:
    appname: vrp-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

feign:
  oauth2:
    enabled: true
management:
  security:
    enabled: false
  trace:
    include: request_headers,response_headers,cookies,authorization_header,errors,path_info,path_translated,context_path,user_principal,parameters,query_string,auth_type,remote_address,session_id,remote_user


security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource





